M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 03:38:51 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T15:38:51-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X4.9Y-3.9
X5.0Y-4.1
X5.1Y-4.0
X5.1Y-4.1
X5.3Y-4.2
X5.6Y-4.0
X5.7Y-3.8
X5.7Y-4.1
T2
X4.8Y-3.6
X5.0Y-3.6
T0
M30
